_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/deformable_optimizer_1x.yml',
  '_base_/obj2seq_r50.yml',
  '_base_/deformable_detr_reader.yml',
]
pretrain_weights: /share/ryan.huang1/temp_bin_1/deformable_detr_r50_1x_coco/model_final
weights: /share/ryan.huang1/temp_bin_1/deformable_detr_r50_1x_coco/model_final
# find_unused_parameters: True
