_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/diffusiondet_r50_fpn.yml',
  '_base_/optimizer_3x.yml',
  '_base_/diffusiondet_reader.yml',
]

use_focal: True
use_fed_loss: False
num_classes: 80
weights: output/model_final

snapshot_epoch: 1


DiffusionDetHead:
  num_proposals: 500

DiffusionDetPostProcess:
  num_proposals: 500
