architecture: Obj2Seq
# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True

Obj2Seq:
  backbone: ResNet
  transformer: Obj2SeqDeformableTransformer
  # detr_head: DeformableDETRHead
  post_process: Obj2SeqMutiClassPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_norm: true
  freeze_at: -1
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4


Obj2SeqDeformableTransformer:
  prompt_indicator: PromptIndicator
  num_queries: 80
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
  num_feature_levels: 4
  num_encoder_points: 4
  num_decoder_points: 4
# PromptIndicator:
#   d_model: 256
#   num_blocks: 2

# DeformableDETRHead:
#   num_mlp_layers: 3

# DETRLoss:
#   loss_coeff: {class: 2, bbox: 5, giou: 2, mask: 1, dice: 1}
#   aux_loss: True

# HungarianMatcher:
#   matcher_coeff: {class: 2, bbox: 5, giou: 2}
